name: Build and Deploy

on:
  # Trigger the workflow on push, but only for the dev branch
  push:
    branches:
      - dev
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Get dependencies
        run: npm install
      - name: Build app
        run: |
          mv ./src/service/api-url-dev ./src/service/api-url.js
          CI=false npm run build
      - name: Deploy to S3
        #        if: github.ref == 'refs/heads/main'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2' # optional: defaults to us-east-1
          SOURCE_DIR: 'build' # optional: defaults to entire repository
